### ISSUE TITLE
header layout funky

### ISSUE THREAD

**Issue by mikelmaron** [osmus/teachosm.org#101]
![screen shot 2016-09-15 at 10 50 50 am](https://cloud.githubusercontent.com/assets/22896/18554438/505c9cee-7b32-11e6-9029-10d14e5644d1.png)

**Comment by Nick-Tallguy** [comment]
Will look like this;  
![screenshot from 2016-10-02 21-31-57](https://cloud.githubusercontent.com/assets/6763965/19024056/ef549bb6-88f3-11e6-82b3-882c0d756c72.png)
![screenshot from 2016-10-02 21-32-20](https://cloud.githubusercontent.com/assets/6763965/19024058/f79d03bc-88f3-11e6-9370-d162a3ec1619.png)

**Comment by jalbertbowden** [comment]
hello teachosm, wondering what the exact issue is? sorry, i'm confused, would like to help

**Comment by shawnmgoulet** [comment]
@osmlab/teachosm - is this still open?  can we close?

**Comment by geomantic** [comment]
OBE
