### ISSUE TITLE
Pre-translation Cleanup

### ISSUE THREAD

**Issue by geomantic** [osmus/teachosm.org#130]
Sort of a running to-do list of things to do prior to next round of translations:

- [ ]  /files directory: Refresh TeachOSM files, jettison obsolete LearnOSM files

- [ ]  /vendor directory: need to update jquery?

**Comment by Nick-Tallguy** [comment]
I've been trying to simplify the setting up of new languages on LearnOSM and have created  
https://github.com/Nick-Tallguy/LearnOSM-language-helper
which automates much of the process of setting up.

In case you are interested in something similar, I have started to setup a similar 'helper' for TeachOSM at https://github.com/Nick-Tallguy/TeachOSM-language-helper

I've paused while waiting to see if this would be of any use and for any discussion on amendments if needed.

**Comment by geomantic** [comment]
Nick,
First, thanks so much for taking this on. I think it could be quite useful in simplifying the setup for new languages. Look forward to the discussion on this.

**Comment by geomantic** [comment]
Deferred.
