### ISSUE TITLE
Update TeachOSM to https

### ISSUE THREAD

**Issue by geomantic** [osmus/teachosm.org#134]
Per Tom Hughes

We are working to deprecate http access to openstreetmap.org and as part of that we need to ensure that all OAuth clients are using https.

Your application at http://tasks.teachosm.org/ has been identified as a recent user of http to access the OAuth API so am writing to ask if you could please update it to use https instead.

I would also point out that you are using an OAuth consumer key that is actually registered to http://tasks.hotosm.org/ and you should probably replace that with one specific to your application.

Thanks for your help,

Tom

**Comment by shawnmgoulet** [comment]
@mikelmaron - I pointed @geomantic to this, but am leaving it here as well for reference for all.  If the domain is through namecheap, this outlines an option to move from http --> https | https://www.namecheap.com/support/knowledgebase/article.aspx/9940/2182/how-to-enable-https-redirection-using-namecheap-ssl-plugin-for-opencart
