### ISSUE TITLE
Captcha not working properly

### ISSUE THREAD

**Issue by geomantic** [osmus/teachosm.org#145]
Ticking the captcha box does not return to allow completion of the step. @shawnmgoulet @d3netxer

**Comment by d3netxer** [comment]
Once a user clicks the captcha box and passes the test, or if the Google captcha test determines you are not a robot, then the captcha box is checked. There is no need to try to uncheck the box.

I'll follow-up with you offline to see if you are experiencing another problem.

**Comment by geomantic** [comment]
Fixed.
