### ISSUE TITLE
OpenStreetMap US url incorrect

### ISSUE THREAD

**Issue by jessbeutler** [osmus/teachosm.org#195]
The hyperlink to OpenStreetMap US in the **About** section currently redirects to openstreetmap.org. It should go to openstreetmap.us

![image](https://user-images.githubusercontent.com/36767434/133148597-2f32b8ba-46a3-44ae-951c-d5e62c0ed78f.png)

**Comment by d3netxer** [comment]
Ok thanks, I updated the link

**Comment by jessbeutler** [comment]
Thank you! This is fixed.
