### ISSUE TITLE
Bad PDF link

### ISSUE THREAD

**Issue by samwilson** [osmus/teachosm.org#202]
The link to the PDF for [Field Mapping with OpenStreetMap](https://teachosm.org/projects/2020-03-10-68709) is broken (status: 403 Forbidden):

https://teachosm-geosurge-content-deploy.s3.amazonaws.com/1583854473711-4_fieldMapping_worksheet_2c.pdf

**Comment by d3netxer** [comment]
Thank you for the notice, I uploaded the correct doc and adjusted the permissions.

**Comment by samwilson** [comment]
Wow, that was quick! Thanks. :-) Looks good now.
