### ISSUE TITLE
Add images to each Case Study. 

### ISSUE THREAD

**Issue by mikelmaron** [osmus/teachosm.org#46]

**Comment by geomantic** [comment]
Get images from Brian DeRocher/MappingDC

**Comment by Nick-Tallguy** [comment]
Adding images is very easy now - navigate using your web browser to <https://github.com/osmlab/teachosm/tree/gh-pages/images> & click on the 
![screenshot from 2016-10-02 23-06-31](https://cloud.githubusercontent.com/assets/6763965/19024138/eeded3e4-88f4-11e6-89a8-17d492601dee.png)
"Upload Files" button.

In the text of the module (.md document) reference the image, such as
     ![screenshot from 2016-10-02 23-15-03](https://cloud.githubusercontent.com/assets/6763965/19024189/25013f10-88f6-11e6-82ef-6324e92ca50b.png)
Specifying the image size is optional - handy for small buttons but not really needed for larger images. Just miss the "{}" symbols and everything in them to have the image full size.

**Comment by geomantic** [comment]
Rendered moot due to content refresh (2021).
