### ISSUE TITLE
build modules for incorporating TeachOSM in longer term project

### ISSUE THREAD

**Issue by mikelmaron** [osmus/teachosm.org#50]
from conceptual problem, geodata need, representation, collection, processing, use

food security is a good continuing theme here

**Comment by mikelmaron** [comment]
start getting thoughts from Melinda, and look at her past syllabus

**Comment by geomantic** [comment]
Closing this as the issue has been recast with 'Couch to QGIS' and similar uses of OSM as on-ramp.
