### ISSUE TITLE
internationalize and localize

### ISSUE THREAD

**Issue by mikelmaron** [osmus/teachosm.org#55]

**Comment by mikelmaron** [comment]
we need a structure

**Comment by geomantic** [comment]
Added directories for Spanish /es and French /fr for initial translation. 

We should consider a bi-annual or quarterly translation cycle once these two are translated.

**Comment by mcawley** [comment]
Did you see the notes I created in the Google doc for translations?

**Comment by mcawley** [comment]
Here is the link: https://docs.google.com/a/boomgeo.com/document/d/1pz4rFp2ROeKjaSNggRPFLBiu7_zRZtQ7pzR0QA9nuKQ/edit?usp=sharing
Many people are interested but the Github editing process was pretty challenging and created a hurdle...

**Comment by geomantic** [comment]
@mcawley I'm seeing your notes now...

**Comment by geomantic** [comment]
Deferring this for now.
