### ISSUE TITLE
Consider sample files being made available via google docs/similar

### ISSUE THREAD

**Issue by CloCkWeRX** [osmus/teachosm.org#63]
There's a sample excel spreadsheet (http://teachosm.org/en/workflow/workflow5/) and sample powerpoint (http://teachosm.org/en/workflow/workflow3/); consider making these available via google docs.

The main advantages of this:
- You can convert to whatever format needed (slight learning curve if someone has never used them before)
- Its easy to 'make a copy', and because of the networked nature of the tool; contribute that back to teachosm/the community
- It features inbuilt comment systems; and multiple editors at once; which make it quite possible for students to ask questions or highlight things which are unclear - this lets us more easily tweak the materials.

**Comment by geomantic** [comment]
Closing this due to link rot.
