### ISSUE TITLE
other guides for reference

### ISSUE THREAD

**Issue by mikelmaron** [osmus/teachosm.org#78]
https://s3-ap-southeast-1.amazonaws.com/myw-media/myw/wp-content/uploads/2014/10/MapYourWorld_StudyGuide_16sessions.pdf

**Comment by geomantic** [comment]
Should we link to this? Or post it on the site? Consider it thoughtfully in our quiet time?

**Comment by geomantic** [comment]
Rendered moot by website redesign.
