### ISSUE TITLE
Update Tasking Manager to the latest version

### ISSUE THREAD

**Issue by geomantic** [osmus/teachosm.org#85]
Think we're a version (or two) behind. Keeping the in sync would be good because there is considerable overlap between those who use HOT TM and those who use TeachOSM TM.

**Comment by mapmeld** [comment]
Not sure if this is related... when I upload this KML file as the boundary, it doesn't show any square tiles.

[cma_layer.kml.zip](https://github.com/osmlab/teachosm/files/73754/cma_layer.kml.zip)

I looked at the network log and the error is a 502 Bad Gateway error when POSTing to http://tasks.teachosm.org/project/grid_simulate

**Comment by geomantic** [comment]
Rendered moot due to current (2021) agreement w/ HOT to maintain TM.
