### ISSUE TITLE
Create an 'About' section

### ISSUE THREAD

**Issue by geomantic** [osmus/teachosm.org#87]
Create an 'About' section that describes on-going activities, so that visitors to TeachOSM.org get a sense of what TeachOSM is actively engaged in.

**Comment by sgoulet** [comment]
@osmlab/teachosm self-assigning

**Comment by shawnmgoulet** [comment]
@geomantic - which route would you like to go with this?  examples being...

- **About** describing the project mission/purpose of TeachOSM **_OR_**
- **About** describing current TeachOSM initiatives linking to workspaces **_OR_**
- **About** being an event calendar **_OR_**
- something else

**Comment by geomantic** [comment]
The first two, but not the third (or fourth). Don't think we have enough yet to warrant a calendar and besides, descriptive stuff could also include dates for events.

**Comment by shawnmgoulet** [comment]
Thanks @geomantic, I will fork & start working on this.

**Comment by geomantic** [comment]
OBE
